import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Building Compliance OS",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-16">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: March 2026</p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By accessing or using Building Compliance OS, you agree to be bound by these Terms of Service.
            If you do not agree, you may not use the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">2. Description of Service</h2>
          <p className="text-muted-foreground">
            Building Compliance OS provides tools for tracking building emissions, calculating compliance with
            local building performance standards (such as NYC Local Law 97), generating compliance reports,
            and managing building portfolios.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">3. User Accounts</h2>
          <p className="text-muted-foreground">
            You are responsible for maintaining the confidentiality of your account credentials and for all activities
            that occur under your account. You must notify us immediately of any unauthorized use.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">4. Data Accuracy</h2>
          <p className="text-muted-foreground">
            You are responsible for the accuracy of data entered into the platform. While we provide calculation
            tools and compliance assessments, these are for informational purposes and do not constitute legal
            or professional compliance advice. Always consult with qualified professionals for official compliance submissions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">5. Subscription and Billing</h2>
          <p className="text-muted-foreground">
            Paid plans are billed monthly or annually as selected. You may cancel at any time, and your access
            will continue until the end of the current billing period. Refunds are handled on a case-by-case basis.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">6. Limitation of Liability</h2>
          <p className="text-muted-foreground">
            Building Compliance OS is provided &quot;as is&quot; without warranties of any kind. We are not liable for
            any penalties, fines, or losses arising from reliance on calculations or reports generated by the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">7. Termination</h2>
          <p className="text-muted-foreground">
            We reserve the right to suspend or terminate accounts that violate these terms. You may delete your
            account at any time, and we will remove your data within 30 days of account deletion.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">8. Changes to Terms</h2>
          <p className="text-muted-foreground">
            We may update these terms from time to time. We will notify you of material changes via email or
            through the platform. Continued use after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">9. Contact</h2>
          <p className="text-muted-foreground">
            For questions about these terms, please contact us at legal@buildingcomplianceos.com.
          </p>
        </section>
      </div>
    </div>
  );
}
