import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);
const fromAddress = process.env.EMAIL_FROM || 'Building Compliance OS <onboarding@resend.dev>';

export interface EmailReportOptions {
  reportBuffer: Buffer;
  recipientEmail: string;
  buildingName: string;
  year: number;
  complianceStatus: string;
  totalEmissions: number;
  emissionsLimit: number;
}

export async function emailReport(options: EmailReportOptions): Promise<{
  success: boolean;
  message: string;
}> {
  const subject = "Compliance Report - " + options.buildingName + " - " + options.year;
  const html = [
    "<p>Dear Recipient,</p>",
    "<p>Please find attached the compliance report for " + options.buildingName + " for the year " + options.year + ".</p>",
    "<p><strong>Summary:</strong></p>",
    "<ul>",
    "<li>Status: " + options.complianceStatus.toUpperCase() + "</li>",
    "<li>Total Emissions: " + options.totalEmissions.toFixed(2) + " tCO2e</li>",
    "<li>Emissions Limit: " + options.emissionsLimit.toFixed(2) + " tCO2e</li>",
    "</ul>",
    "<p>This report was generated by Building Compliance OS.</p>",
    "<p>Best regards,<br/>Building Compliance OS</p>",
  ].join("\n");

  try {
    const { error } = await resend.emails.send({
      from: fromAddress,
      to: options.recipientEmail,
      subject,
      html,
      attachments: [
        {
          filename: "compliance-report-" + options.year + ".pdf",
          content: options.reportBuffer,
        },
      ],
    });

    if (error) {
      return { success: false, message: error.message };
    }

    return { success: true, message: "Email sent to " + options.recipientEmail };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to send email";
    return { success: false, message };
  }
}
